### ISSUE TITLE
Can't submit participant agreement form successfully?

### ISSUE THREAD

**Issue by aphillips** [whatwg/participant-data#24]
When our legal representative went to submit the participation agreement for "Amazon.com Services LLC" we get a 400:

![image](https://user-images.githubusercontent.com/69082/78693101-a1f4b400-78af-11ea-85d8-1f88c3befb4a.png)

Can someone check what happened? I can provide the relevant information for our organization or submit a PR as needed.

**Comment by domenic** [comment]
Eek. I will look into this immediately.

**Comment by domenic** [comment]
I am not able to reproduce this locally, using that entity name. That error should only occur if the entity name field is empty... in which case the form should not be possible to submit. I also submitted a test entity on the live site which had no problems.

Could you try again? Perhaps with a screenshot of the filled-out form beforehand? Looking at what your network panel sends would also be helpful.

I wonder if there's something possible with an older browser which is not possible in any of the modern ones that we test on?

**Comment by aphillips** [comment]
I can try it. This was a VP doing it and I'm not sure what they actually typed. I'll either repro it or have a successful submit. Stay tuned.

**Comment by aphillips** [comment]
@domenic I finally got them to submit again. Can you check if it worked?

**Comment by domenic** [comment]
Unfortunately I don't see any results in https://github.com/whatwg/participant-data/commits/master :(.

**Comment by aphillips** [comment]
@domenic thanks. I didn't see it either, but wasn't sure if there was some interstitial thing. I'll see if I can get approval to submit the form myself (I'm getting a VP to click the button and that's not working out) or just send the data. Stay tuned.

**Comment by aphillips** [comment]
It was operator error.
