### ISSUE TITLE
Verification of Cloudflare

### ISSUE THREAD

**Issue by annevk** [whatwg/participant-data#3]
@terinjokes since your title is Systems Engineer, I was wondering if you're authorized to make this commitment fc5d05fd60d32655540c052b770094bd6edc3d68 on behalf of Cloudflare.

Thanks!

cc @dknecht @whatwg/sg

**Comment by dknecht** [comment]
I will resubmit today with me as signatory.

**Comment by dknecht** [comment]
Actually can I just approve @terinjokes?

**Comment by annevk** [comment]
Okay, per https://www.cloudflare.com/people/ you're Head of Product Strategy. That seems good enough to me, thanks!
