### ISSUE TITLE
unsure about participation/affiliation 

### ISSUE THREAD

**Issue by marcoscaceres** [whatwg/participant-data#55]
Sorry for the silly question... I'm currently listed here:

https://github.com/whatwg/participant-data/blob/main/individuals.json#L2370

But I'm now affiliated with Apple (hi @dwsinger + @hober). 

Could someone provide me with some guidance as to next steps? I'd like to contribute to HTML, WebIDL, and, if possible, all work streams.

**Comment by domenic** [comment]
Exciting!

Send a PR to remove yourself from individuals.json, and per [entities.json](https://github.com/whatwg/participant-data/blob/main/entities.json), make sure you have a publicly-visible (e.g., while logged out) membership of the apple-whatwg GitHub organization. That should do it!

**Comment by marcoscaceres** [comment]
Thanks @domenic. I'll ask @hober to add me over in apple-whatwg.
