### ISSUE TITLE
Automattic signed the agreement twice

### ISSUE THREAD

**Issue by annevk** [whatwg/participant-data#77]
@jsnajdr @jishudev1 it seems you signed the agreement first for a number of Workstreams: https://github.com/whatwg/participant-data/blob/main/entities.json#L1527-L1570

@dmsnell @adamziel you then signed the agreement again for all Workstreams two months ago: https://github.com/whatwg/participant-data/blob/main/entities.json#L1730-L1755

How would you like to resolve this? (It also seems some of the fields are inconsistent between these two entries.)

cc @zcorpan

**Comment by dmsnell** [comment]
oh I wasn't aware @annevk - it was rather confusing when I signed, particularly on the aspect of whether I was participating as an individual or representing my employer. can you advise on what choices need to be made for resolution? I'm not sure what they are.

**Comment by annevk** [comment]
This can be resolved by a PR deduplicating the entries, ideally with both of those having signed explicitly consenting to the changes or someone else with the relevant authority at Automattic.
